name: pioneer_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  bloc: ^8.1.4
  connectivity_plus: ^6.0.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.1
  get_it: ^7.6.7
  go_router: ^6.2.0
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.0.18
  smooth_page_indicator: ^1.1.0
  flutter_snake_navigationbar: ^0.6.1

 
  #percent_indicator: ^2.1.9+1
  #flutter_swiper: ^1.1.6
  #scrollable_positioned_list: ^0.3.8




dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon/launcher_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/pioneer-logo.png

  android_12:
    image: assets/images/pioneer-logo.png
    icon_background_color: "#ffffff"

  web: false
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/flags/
    - assets/images/on_boarding/
    - assets/icons/logo/
    - assets/icons/auth/
    - assets/images/about/
    - assets/icons/bottom_nav_bar/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
